import type { ReactElement } from 'react';
import { HomePage } from './pages/HomePage';
import { LogsPage } from './pages/LogsPage/LogsPage';
import { PoolPage } from './pages/PoolPage/PoolPage';
import { TestPage } from './pages/TestPage';
import { detectPage } from './types/window';

export function App(): ReactElement {
  const page = detectPage();
  if (!page) {
    return (
      <div className="p-6 text-center text-sm text-slate-500 dark:text-slate-400">
        No report payload found on <code>window</code>. Was the report generated by
        Marathon 2+?
      </div>
    );
  }
  switch (page.kind) {
    case 'index':
      return <HomePage data={page.payload as never} />;
    case 'pool':
      return <PoolPage data={page.payload as never} />;
    case 'test':
      return <TestPage data={page.payload as never} />;
    case 'logs':
      return <LogsPage data={page.payload as never} />;
  }
}
