import clsx from 'clsx';
import type { ReactNode } from 'react';
import { useTheme } from '../theme/ThemeProvider';
import { formatTimestamp } from '../util/time';

interface AppShellProps {
  title: ReactNode;
  breadcrumbs?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
}

/**
 * Chrome shared by every emitted page. Kept intentionally light — pages own
 * their own inner layout. `breadcrumbs` renders inline links to sibling files
 * (`../index.html`, `<pool>.html`, etc.) since navigation between emitted
 * pages is via on-disk `href`s, not client-side routing.
 */
export function AppShell({ title, breadcrumbs, actions, children }: AppShellProps) {
  const { resolved, toggle } = useTheme();
  return (
    <div className="flex min-h-screen flex-col bg-surface text-slate-900 dark:text-slate-100">
      <header
        className={clsx(
          'sticky top-0 z-20 border-b border-surface-border bg-surface/95 backdrop-blur',
          'flex items-center gap-4 px-4 py-3',
        )}
      >
        <div className="flex flex-col gap-1 min-w-0">
          <div className="text-lg font-semibold truncate">{title}</div>
          {breadcrumbs && (
            <div className="text-xs text-slate-500 dark:text-slate-400 truncate">
              {breadcrumbs}
            </div>
          )}
        </div>
        <div className="flex-1" />
        {actions}
        <button
          type="button"
          onClick={toggle}
          aria-label={`Switch to ${resolved === 'dark' ? 'light' : 'dark'} theme`}
          className="rounded-md border border-surface-border bg-surface-alt px-2 py-1 text-sm hover:bg-slate-100 dark:hover:bg-slate-700"
        >
          {resolved === 'dark' ? '☀ light' : '☾ dark'}
        </button>
      </header>
      <main className="flex-1 px-4 py-4">{children}</main>
      <ReportFooter />
    </div>
  );
}

/**
 * "Generated by Marathon at …" line, centered under the last content block
 * and following it in flow (no fixed positioning). Reads the timestamp from
 * `window.reportGeneratedAt` which the Kotlin reporter emits on every page.
 */
function ReportFooter() {
  const generatedAt = typeof window !== 'undefined' ? window.reportGeneratedAt : undefined;
  if (typeof generatedAt !== 'number') return null;
  return (
    <footer className="mt-8 border-t border-surface-border px-4 py-4 text-center text-xs text-slate-500 dark:text-slate-400">
      Generated by Marathon at {formatTimestamp(generatedAt)}
    </footer>
  );
}
