plugins {
    idea
    `java-library`
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.dokka")
    jacoco
    id("com.github.gmazzo.buildconfig")
}

// Kotlin plugin registers a matching Kotlin source set for each Java one;
// applying `kotlin.srcDirs(...)` after the `create` block works without the
// Gradle 9-removed `withConvention` shim.
sourceSets {
    create("integrationTest") {
        compileClasspath += sourceSets["main"].output
        compileClasspath += sourceSets["test"].output
        compileClasspath += configurations.testCompileClasspath.get()

        runtimeClasspath += sourceSets["main"].output
        runtimeClasspath += sourceSets["test"].output
        runtimeClasspath += configurations.testRuntimeClasspath.get()

        java.srcDirs("src/integrationTest/kotlin")
    }
}

buildConfig {
    useKotlinOutput { internalVisibility = false }

    buildConfigField("String", "NAME", "\"${project.name}\"")
    buildConfigField("String", "VERSION", provider<String> { "\"${Deployment.getVersion(project)}\"" })
    buildConfigField("String", "BUGSNAG_TOKEN", provider {
        val token = System.getenv("BUGSNAG_TOKEN") ?: ""
        "\"$token\""
    })
    buildConfigField("String", "RELEASE_MODE", provider {
        val releaseMode = Deployment.releaseMode ?: ""
        "\"$releaseMode\""
    })
}

dependencies {
    api(project(":configuration"))
    implementation(project(":report:html-report"))
    implementation(project(":report:execution-timeline"))

    implementation(libs.allure)
    implementation(libs.allureKotlinCommons)
    implementation(libs.allureEnvironment)
    implementation(libs.allureTestFilter)

    implementation(project(":analytics:usage"))
    implementation(libs.gson)
    implementation(libs.jacksonAnnotations)
    implementation(libs.apacheCommonsIO)
    implementation(libs.kotlinStdLib)
    implementation(libs.kotlinCoroutines)
    implementation(libs.kotlinLogging)
    implementation(libs.logbackClassic)
    implementation(libs.influxDbClient)
    implementation(libs.influxDb2Client)
    implementation(libs.scalr)
    api(libs.koin)
    api(libs.bugsnag)
    testImplementation(project(":vendor:vendor-test"))
    testImplementation(libs.junit5)
    testImplementation(libs.kluent)
    testImplementation(libs.assertk)
    testImplementation(libs.testContainers)
    testImplementation(libs.testContainersInflux)
    testImplementation(libs.mockitoKotlin)
    testImplementation(libs.koinTest)
    testImplementation(libs.xmlUnit)
    testImplementation(libs.coroutinesTest)
    testRuntimeOnly(libs.jupiterEngine)
    testRuntimeOnly(libs.junitPlatformLauncher)
    // integrationTest source set has its own runtime configuration; without the
    // launcher on that classpath Gradle 9's worker fails with
    // "Failed to load JUnit Platform" before any test even starts.
    "integrationTestRuntimeOnly"(libs.jupiterEngine)
    "integrationTestRuntimeOnly"(libs.junitPlatformLauncher)
}

/**
 * Rebuild the html-report preview fixture directly through the real Kotlin
 * reporter pipeline. Wraps the `HtmlReportFixtureGenerator` JUnit class so
 * a human can `./gradlew :core:generateHtmlReportFixture` without hunting
 * for the `--tests "*Fixture*"` filter. Output lands in
 * `core/build/fixtures/{android,ios}/html/`. Depends on the bundle copy so
 * the app.min.{js,css} the reporter reads at runtime are present.
 */
tasks.register<Test>("generateHtmlReportFixture") {
    description = "Emit an html-report preview into core/build/fixtures via real Kotlin reporters."
    group = "html-report"
    // The html-report bundle is generated by Vite through gradle-node-plugin
    // and packaged into the module jar via processResources. Depending on the
    // sibling module's processResources guarantees the fresh bundle is on the
    // runtime classpath when the fixture reporter reads it.
    dependsOn(":report:html-report:processResources")
    testClassesDirs = sourceSets["test"].output.classesDirs
    classpath = sourceSets["test"].runtimeClasspath
    useJUnitPlatform()
    filter {
        includeTestsMatching("com.malinskiy.marathon.report.html.HtmlReportFixtureGenerator")
    }
    // Keep this out of `check` — heavy IO, only run on demand.
    outputs.upToDateWhen { false }

    // Forward scale knobs from Gradle project properties into JVM sysprops
    // the fixture generator reads. Example:
    //   ./gradlew :core:generateHtmlReportFixture -PfixturePools=8 -PfixtureTests=10000
    listOf("fixturePools", "fixtureTests", "fixtureDevicesPerPool").forEach { key ->
        (project.findProperty(key) as? String)?.let { systemProperty(key, it) }
    }
    // Larger scales blow past the default 512m heap — reporter builds the
    // full ExecutionReport in memory before emit.
    maxHeapSize = "2g"
}

tasks.register<Test>("integrationTest") {
    description = "Runs integration tests."
    group = "verification"

    testClassesDirs = sourceSets["integrationTest"].output.classesDirs
    classpath = sourceSets["integrationTest"].runtimeClasspath

    exclude("**/resources/**")

    shouldRunAfter("test")
}

setupDeployment()
setupKotlinCompiler()
setupTestTask()
