{
 "title": "Marathon tests",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "retentionPolicy", "query": "SHOW RETENTION POLICIES" }
  ]
 },
 "panels": [
  {
   "title": "Test executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Tests count",
     "measurement": "tests",
     "query": "SELECT count(\"success\") FROM $retentionPolicy.\"tests\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",ignored=\"true\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Ignored",
     "measurement": "tests",
     "query": "SELECT count(\"success\") FROM $retentionPolicy.\"tests\" WHERE ignored = 1 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ignored", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Failing tests count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",success=\"false\",})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Failing",
     "measurement": "tests",
     "query": "SELECT count(\"success\") FROM $retentionPolicy.\"tests\" WHERE success = 0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failing tests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_testname",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",success=\"false\"}) by (class,method)",
     "legendFormat": "{{class}},{{method}}",
     "measurement": "tests",
     "query": "SELECT count(\"success\") FROM $retentionPolicy.\"tests\" WHERE success = 0 AND $timeFilter GROUP BY time($__interval), \"testname\" fill(null)\n",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "success", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Failing test classes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_class",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",success=\"false\"}) by (class)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{class}}",
     "query": "SELECT count(\"success\") FROM $retentionPolicy.\"tests\" WHERE success = 0 AND $timeFilter GROUP BY time($__interval), \"class\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failing devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceSerial",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",success=\"false\"}) by (deviceserial)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{deviceserial}}",
     "query": "SELECT count(\"success\") FROM $retentionPolicy.\"tests\" WHERE success = 0 AND $timeFilter GROUP BY time($__interval), \"deviceSerial\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}