{
 "title": "Marathon tests",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Test executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aggregate(tests.*.*.*.*.*.success, \"sum\")"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aggregate(tests.*.*.*.*.*.ignored, \"sum\")"
    }
   ]
  },
  {
   "title": "Failing tests count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "diffSeries(aggregate(tests.*.*.*.*.*.success, \"count\"), aggregate(tests.*.*.*.*.*.success, \"sum\"))"
    }
   ]
  },
  {
   "title": "Failing tests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(offset(removeAboveValue(tests.*.*.*.*.*.success, 0.5), 1), 1, \"sum\")"
    }
   ]
  },
  {
   "title": "Failing test classes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(offset(removeAboveValue(tests.*.*.*.*.*.success, 0.5), 1), 3, \"sum\")"
    }
   ]
  },
  {
   "title": "Failing devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(offset(removeAboveValue(tests.*.*.*.*.*.success, 0.5), 1), 5, \"sum\")"
    }
   ]
  }
 ]
}