{
 "title": "Marathon tests [InfluxDB v2]",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Test executions [pass/fail]",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Tests count",
     "measurement": "tests",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tests\" and\n    r._field == \"success\"\n  )",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "count",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",ignored=\"true\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Ignored",
     "measurement": "tests",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tests\" and\n    r._field == \"ignored\" and\n    r._value == 1.0\n  )\n  |> group(columns: [\"testname\"])\n  |> count()",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ignored", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Failing tests",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "count",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",success=\"false\",})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Failing",
     "measurement": "tests",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tests\" and\n    r._field == \"success\" and\n    r._value == 0.0\n  )\n  |> group(columns: [\"testname\"])\n  |> count()",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total testing time per test",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_deviceSerial",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",success=\"false\"}) by (deviceserial)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{deviceserial}}",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tests\" and\n    r._field == \"duration\"\n  )\n  |> group(columns: [\"testname\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({\n    time: r._time,\n    source: r.testname,\n    duration: r._value\n  }))\n  |> sort(columns: [\"duration\"], desc: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failing devices",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_deviceSerial",
     "expr": "count(android_test{deviceserial=~\"$device\",branch=~\"$branch\",class=~\"$class\",build_id=~\"$build_id\",team=~\"$team\",success=\"false\"}) by (deviceserial)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{deviceserial}}",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tests\" and\n    r._field == \"success\" and\n    r._value == 0.0\n  )\n  |> group(columns: [\"deviceSerial\"])\n  |> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}